version: '3.7'
services:
    mysql57:
        image: mysql:5.7
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - './mysql/init:/docker-entrypoint-initdb.d/'
            - './mysql/conf/my.cnf:/etc/my.cnf'
        ports:
            - '3306:3306'
    redis:
        image: redis:latest
        container_name: redis_db
        command: redis-server --requirepass 123456
        ports:
            - '6379:6379'
