version: '3.7'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        container_name: javabook-server01
        volumes:
            - './jar:/home/work'
