version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./volumes/clickhouse:/var/lib/clickhouse
